name: ppo_rad
channels:
  - numba
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=1.11
  - scipy
  - gym
  - numba
  - black
  - swig
  - pip
  - pip:
      - -e ./gym_rad_search
