name: ppo_rad
channels:
  - conda-forge
  - anaconda
  - pytorch
  - numba
dependencies:
  - python=3.9
  - black
  - pip
  - pytorch=1.8
  - scipy
  - psutil
  - mpi4py
  - joblib
  - statsmodels
  - matplotlib
  - numba
  - pandas
  - swig
  - gym
  - pip:
      - git+https://github.com/peproctor/PyVisiLibity.git@c76020079110231f882f38f61b3ab25d01de21f0
      - git+https://github.com/peproctor/REU_rl.git@350797ef99bf8405a95f8b8b7e1be3292ce41d11
      - ./gym_rad_search
