name: ppo_rad
channels:
  - conda-forge
  - anaconda
  - pytorch
  - numba
dependencies:
  - python
  - black
  - pip
  - pytorch=1.8
  - scipy
  - psutil
  - mpi4py
  - joblib
  - statsmodels
  - matplotlib
  - numba
  - pandas
  - swig
  - pip:
      - git+https://github.com/peproctor/PyVisiLibity.git
      - git+https://github.com/peproctor/REU_rl.git
      - gym==0.20.0
      - ./gym_rad_search
