name: Build and run

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Conda environment from environment.yml
        uses: mamba-org/provision-with-micromamba@v11
        with:
          environment-file: environment.yml
          environment-name: ppo_rad
      - name: Run Python
        shell: bash -l {0}
        run: |
          cd algos/ppo/
          python ppo.py --seed 0 --cpu 1 --exp_name exp1 --epochs 10 &> tee ../../output.txt
      - uses: actions/upload-artifact@v3
        with:
          path: |
            output.txt
            models
