name: Build and run

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash -l {0}

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Conda environment from environment.yml
        uses: mamba-org/provision-with-micromamba@v11
        with:
          environment-file: environment.yml
          environment-name: ppo_rad
      - name: Run Python
        run: |
          cd algos/ppo/
          python ppo.py --seed 0 --cpu 1 --exp_name exp1 --epochs 10 | tee ../../output.txt
      - name: Log output to summary
        run: |
          echo "# Epoch results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "```log" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          cat output.txt >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "```" >> $GITHUB_STEP_SUMMARY
      - uses: actions/upload-artifact@v3
        with:
          path: |
            output.txt
            models
